/**
 * Per-carrier rich inspection records.
 * Each carrier has its own distinct inspection history so counts vary by carrier.
 * Violation codes and severity match the carrier risk profiles in mock-carriers.ts.
 */
import type { RichInspection } from './types';

// ── ACME Transport LLC (USDOT 491180) — 6 inspections, elevated risk ──
const acmeRich: RichInspection[] = [
  {
    id: 'ACME-001',
    date: '2025-03-12',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Columbus', state: 'OH' },
    driverName: 'John Miller',
    vin: '1FUJGLBG4CLBH8412',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2021,
    plateNumber: 'OH8842B',
    plateState: 'OH',
    reportNumber: 'OHI041200456',
    reportState: 'OH',
    startTime: '10:15',
    endTime: '11:50',
    facility: 'I-70 Weigh Station, Columbus',
    driverOOS: true,
    vehicleOOS: true,
    severityScore: 8,
    status: 'New',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — pushrod travel exceeds maximum limit',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 3,
        oos: true,
      },
      {
        code: '391.11(b)(4)',
        description: 'Medical certificate — operating a CDL vehicle while self-certified as excepted with SDLA',
        severity: 'Major',
        basicCategory: 'Driver Qualification',
        timeWeight: 3,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'repeat-violation',
        label: 'Repeat Brake Issue',
        description: 'This is the 3rd brake violation for vehicles in this terminal over 6 months',
        riskLevel: 'High',
        suggestedActions: [
          'Schedule immediate brake inspection for all fleet units',
          'Review pre-trip inspection logs for the past 90 days',
          'Implement mandatory brake check at gate departure',
        ],
      },
    ],
    notes: [],
  },
  {
    id: 'ACME-002',
    date: '2025-01-22',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Indianapolis', state: 'IN' },
    driverName: 'Sarah Chen',
    vin: '3AKJHHDRXGSGF3214',
    vehicleMake: 'Kenworth',
    vehicleModel: 'T680',
    vehicleYear: 2022,
    plateNumber: 'IN7734C',
    plateState: 'IN',
    reportNumber: 'IND082200891',
    reportState: 'IN',
    startTime: '14:30',
    endTime: '15:45',
    facility: 'I-465 Port of Entry',
    driverOOS: false,
    vehicleOOS: true,
    severityScore: 7,
    status: 'In Progress',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — automatic slack adjuster not functioning properly',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 3,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'high-csa-impact',
        label: 'High CSA Impact',
        description: 'Brake violations are the #1 contributor to your Vehicle Maintenance BASIC score',
        riskLevel: 'High',
        suggestedActions: [
          'File DataQ challenge if inspection data is inaccurate',
          'Document corrective action plan within 48 hours',
        ],
      },
    ],
    notes: ['Vehicle sent to nearest certified repair facility'],
  },
  {
    id: 'ACME-003',
    date: '2024-11-05',
    level: 'II',
    type: 'Roadside',
    location: { city: 'Pittsburgh', state: 'PA' },
    driverName: 'David Rodriguez',
    vin: '1XPWD49X1ED215678',
    vehicleMake: 'Peterbilt',
    vehicleModel: '389',
    vehicleYear: 2020,
    plateNumber: 'PA4491X',
    plateState: 'PA',
    reportNumber: 'PAE071100234',
    reportState: 'PA',
    startTime: '09:00',
    endTime: '09:55',
    facility: 'PA Turnpike Troop D Barracks',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 7,
    status: 'Resolved',
    violations: [
      {
        code: '395.8(e)(1)',
        description: 'False record of duty status — ELD log does not accurately reflect driver hours',
        severity: 'Major',
        basicCategory: 'HOS Compliance',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'audit-risk',
        label: 'ELD Audit Risk',
        description: 'HOS log falsification triggers elevated audit probability under FMCSA targeting',
        riskLevel: 'Medium',
        suggestedActions: [
          'Conduct internal ELD audit for this driver',
          'Review driver trip records for past 30 days',
          'Schedule HOS compliance refresher training',
        ],
      },
    ],
    notes: ['Driver completed HOS re-training on 11/12'],
  },
  {
    id: 'ACME-004',
    date: '2024-09-08',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Lexington', state: 'KY' },
    driverName: 'Marcus Thompson',
    vin: '1FUJGLBG4CLBH9921',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2021,
    plateNumber: 'KY2293T',
    plateState: 'KY',
    reportNumber: 'KYW093100567',
    reportState: 'KY',
    startTime: '16:20',
    endTime: '17:30',
    facility: 'I-64 Rest Area MM 94',
    driverOOS: false,
    vehicleOOS: true,
    severityScore: 8,
    status: 'Resolved',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — brake lining thickness below minimum',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'likely-reoccur',
        label: 'Likely to Reoccur',
        description: 'Brake lining wear pattern suggests PM schedule is too infrequent',
        riskLevel: 'High',
        suggestedActions: [
          'Reduce brake inspection interval to every 10,000 miles',
          'Inspect all fleet units for lining thickness this week',
        ],
      },
    ],
    notes: ['Brakes replaced roadside. Vehicle cleared for re-entry.'],
  },
  {
    id: 'ACME-005',
    date: '2024-06-18',
    level: 'III',
    type: 'Roadside',
    location: { city: 'Columbus', state: 'OH' },
    driverName: 'James Wilson',
    vin: '3AKJHHDRXGSGF4455',
    vehicleMake: 'Kenworth',
    vehicleModel: 'T680',
    vehicleYear: 2019,
    plateNumber: 'OH3312W',
    plateState: 'OH',
    reportNumber: 'OHI061800912',
    reportState: 'OH',
    startTime: '08:45',
    endTime: '09:20',
    facility: 'I-270 Commercial Vehicle Inspection Station',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 6,
    status: 'Resolved',
    violations: [
      {
        code: '395.8(e)(1)',
        description: 'False record of duty status — unaccounted driving time on ELD',
        severity: 'Major',
        basicCategory: 'HOS Compliance',
        timeWeight: 1,
        oos: true,
      },
    ],
    aiInsights: [],
    notes: [],
  },
  {
    id: 'ACME-006',
    date: '2024-04-25',
    level: 'II',
    type: 'Roadside',
    location: { city: 'Charleston', state: 'WV' },
    driverName: 'Patricia Lee',
    vin: '1XPWD49X1ED216790',
    vehicleMake: 'Peterbilt',
    vehicleModel: '389',
    vehicleYear: 2020,
    plateNumber: 'WV8871P',
    plateState: 'WV',
    reportNumber: 'WVE042500345',
    reportState: 'WV',
    startTime: '11:30',
    endTime: '12:15',
    facility: 'WV Turnpike Station 14',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 6,
    status: 'Resolved',
    violations: [
      {
        code: '391.11(b)(4)',
        description: 'Medical certificate — driver self-certification category does not match operation type',
        severity: 'Major',
        basicCategory: 'Driver Qualification',
        timeWeight: 1,
        oos: true,
      },
    ],
    aiInsights: [],
    notes: ['Driver provided corrected self-certification within 3 days'],
  },
];

// ── Midwest Logistics Partners (USDOT 847291) — 2 inspections, low risk ──
const midwestRich: RichInspection[] = [
  {
    id: 'MWLP-001',
    date: '2025-02-14',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Chicago', state: 'IL' },
    driverName: 'Robert Johnson',
    vin: '1FUJGLBG4NLBM2211',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2023,
    plateNumber: 'IL9945R',
    plateState: 'IL',
    reportNumber: 'ILI021400123',
    reportState: 'IL',
    startTime: '13:00',
    endTime: '14:10',
    facility: 'I-80 Weigh Station, Alsip',
    driverOOS: false,
    vehicleOOS: false,
    severityScore: 3,
    status: 'Resolved',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — minor pushrod travel exceedance on trailer axle',
        severity: 'Minor',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 3,
        oos: false,
      },
    ],
    aiInsights: [],
    notes: ['Adjusted brakes on-site. No OOS issued.'],
  },
  {
    id: 'MWLP-002',
    date: '2024-10-08',
    level: 'III',
    type: 'Compliance',
    location: { city: 'Kansas City', state: 'MO' },
    driverName: 'Linda Martinez',
    vin: '3AKJHHDRXFSGM3344',
    vehicleMake: 'Peterbilt',
    vehicleModel: '579',
    vehicleYear: 2022,
    plateNumber: 'MO7712L',
    plateState: 'MO',
    reportNumber: 'MOS100800456',
    reportState: 'MO',
    startTime: '10:30',
    endTime: '11:00',
    facility: 'FMCSA Terminal Compliance Check',
    driverOOS: false,
    vehicleOOS: false,
    severityScore: 2,
    status: 'Resolved',
    violations: [
      {
        code: '395.8(e)(1)',
        description: 'Record of duty status — minor discrepancy in on-duty time recording',
        severity: 'Minor',
        basicCategory: 'HOS Compliance',
        timeWeight: 1,
        oos: false,
      },
    ],
    aiInsights: [],
    notes: [],
  },
];

// ── Delta Freight Services Inc (USDOT 562843) — 4 inspections, moderate risk ──
const deltaRich: RichInspection[] = [
  {
    id: 'DLTA-001',
    date: '2025-03-02',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Atlanta', state: 'GA' },
    driverName: 'Kevin Davis',
    vin: '1FUJGLBG4MLBA1122',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2020,
    plateNumber: 'GA5566K',
    plateState: 'GA',
    reportNumber: 'GAE030200789',
    reportState: 'GA',
    startTime: '07:50',
    endTime: '09:15',
    facility: 'I-75 Commercial Vehicle Enforcement Station',
    driverOOS: false,
    vehicleOOS: true,
    severityScore: 8,
    status: 'New',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — pushrod travel exceeds maximum on steer axle',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 3,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'high-csa-impact',
        label: 'High CSA Impact',
        description: 'Steer axle brake violations carry the highest severity weight in Vehicle Maintenance BASIC',
        riskLevel: 'High',
        suggestedActions: [
          'Inspect all fleet steer axle brake assemblies this week',
          'Review pre-trip inspection sign-off process',
        ],
      },
    ],
    notes: [],
  },
  {
    id: 'DLTA-002',
    date: '2024-12-15',
    level: 'II',
    type: 'Roadside',
    location: { city: 'Columbia', state: 'SC' },
    driverName: 'Emma Wilson',
    vin: '1XPWD49X2ED218899',
    vehicleMake: 'Peterbilt',
    vehicleModel: '389',
    vehicleYear: 2019,
    plateNumber: 'SC3318E',
    plateState: 'SC',
    reportNumber: 'SCW121500234',
    reportState: 'SC',
    startTime: '12:10',
    endTime: '13:00',
    facility: 'SC I-20 Inspection Station',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 6,
    status: 'In Progress',
    violations: [
      {
        code: '391.11(b)(4)',
        description: 'Medical certificate — operating a CDL vehicle while self-certified as excepted with SDLA',
        severity: 'Major',
        basicCategory: 'Driver Qualification',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'audit-risk',
        label: 'Audit Risk',
        description: 'Medical certificate violations increase DOT compliance audit likelihood',
        riskLevel: 'Medium',
        suggestedActions: [
          'Audit all driver medical certificate expiration dates immediately',
          'Implement 60-day advance renewal notification system',
        ],
      },
    ],
    notes: [],
  },
  {
    id: 'DLTA-003',
    date: '2024-09-10',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Charlotte', state: 'NC' },
    driverName: 'Christopher Moore',
    vin: '3AKJHHDRXESGM5577',
    vehicleMake: 'Kenworth',
    vehicleModel: 'T680',
    vehicleYear: 2021,
    plateNumber: 'NC6634C',
    plateState: 'NC',
    reportNumber: 'NCE091000567',
    reportState: 'NC',
    startTime: '15:40',
    endTime: '16:50',
    facility: 'I-85 DOT Inspection Station',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 7,
    status: 'Resolved',
    violations: [
      {
        code: '395.8(e)(1)',
        description: 'False record of duty status — driver exceeded 11-hour driving limit per ELD data',
        severity: 'Major',
        basicCategory: 'HOS Compliance',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [],
    notes: ['Driver placed OOS, replacement driver dispatched'],
  },
  {
    id: 'DLTA-004',
    date: '2024-06-05',
    level: 'II',
    type: 'Roadside',
    location: { city: 'Atlanta', state: 'GA' },
    driverName: 'Amanda Taylor',
    vin: '1FUJGLBG4MLBA3344',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2020,
    plateNumber: 'GA7721A',
    plateState: 'GA',
    reportNumber: 'GAW060500891',
    reportState: 'GA',
    startTime: '08:30',
    endTime: '09:10',
    facility: 'I-285 Commercial Vehicle Enforcement',
    driverOOS: false,
    vehicleOOS: false,
    severityScore: 3,
    status: 'Resolved',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — automatic slack adjuster not maintaining proper clearance',
        severity: 'Minor',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 1,
        oos: false,
      },
    ],
    aiInsights: [],
    notes: [],
  },
];

// ── HazTech Specialized Carriers (USDOT 934521) — 4 inspections, hazmat elevated ──
const haztechRich: RichInspection[] = [
  {
    id: 'HZTC-001',
    date: '2025-02-28',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Houston', state: 'TX' },
    driverName: 'John Smith',
    vin: '1HGBH41JXMN109186',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2022,
    plateNumber: 'TX1234J',
    plateState: 'TX',
    reportNumber: 'TXI022800345',
    reportState: 'TX',
    startTime: '14:35',
    endTime: '15:20',
    facility: 'I-45 Weigh Station, Houston',
    driverOOS: true,
    vehicleOOS: true,
    severityScore: 8,
    status: 'New',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — service brake chamber inoperative',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 3,
        oos: true,
      },
      {
        code: '395.8(e)(1)',
        description: 'False record of duty status — ELD shows unaccounted on-duty time',
        severity: 'Major',
        basicCategory: 'HOS Compliance',
        timeWeight: 3,
        oos: false,
      },
    ],
    aiInsights: [
      {
        type: 'repeat-violation',
        label: 'Repeat HOS Issue',
        description: 'This driver has had 3 HOS violations in the past 6 months',
        riskLevel: 'High',
        suggestedActions: [
          'Schedule HOS training immediately',
          'Review ELD device usage and configuration',
          'Implement weekly log audits for 90 days',
        ],
      },
      {
        type: 'high-csa-impact',
        label: 'High CSA Impact',
        description: 'This violation significantly impacts your CSA BASIC scores in Vehicle Maintenance and HOS',
        riskLevel: 'High',
        suggestedActions: [
          'Document corrective action plan within 48 hours',
          'File DataQ challenge if any data is inaccurate',
        ],
      },
    ],
    notes: [],
  },
  {
    id: 'HZTC-002',
    date: '2024-11-07',
    level: 'II',
    type: 'Roadside',
    location: { city: 'New Orleans', state: 'LA' },
    driverName: 'Maria Garcia',
    vin: '2FMZA5142WBA12345',
    vehicleMake: 'Peterbilt',
    vehicleModel: '579',
    vehicleYear: 2021,
    plateNumber: 'LA5678M',
    plateState: 'LA',
    reportNumber: 'LAW110700678',
    reportState: 'LA',
    startTime: '09:15',
    endTime: '10:05',
    facility: 'LA State Patrol Station 14',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 6,
    status: 'In Progress',
    violations: [
      {
        code: '391.11(b)(4)',
        description: 'Medical certificate — driver self-certification category does not match hazmat operation type',
        severity: 'Major',
        basicCategory: 'Driver Qualification',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'audit-risk',
        label: 'High Audit Risk',
        description: 'Medical certificate violations increase the likelihood of a targeted DOT compliance audit',
        riskLevel: 'Medium',
        suggestedActions: [
          'Implement automated certificate expiration tracking',
          'Review all driver certification expiration dates this week',
          'Establish 60-day advance renewal reminders',
        ],
      },
    ],
    notes: ['Driver provided updated medical certificate on 11/08'],
  },
  {
    id: 'HZTC-003',
    date: '2024-08-12',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Oklahoma City', state: 'OK' },
    driverName: 'Robert Johnson',
    vin: '3GNDA23P96S123456',
    vehicleMake: 'Kenworth',
    vehicleModel: 'T680',
    vehicleYear: 2020,
    plateNumber: 'OK9012R',
    plateState: 'OK',
    reportNumber: 'OKE081200912',
    reportState: 'OK',
    startTime: '11:45',
    endTime: '12:30',
    facility: 'I-40 Rest Area Mile Marker 142',
    driverOOS: false,
    vehicleOOS: true,
    severityScore: 8,
    status: 'Resolved',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — brake drum cracked through',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'likely-reoccur',
        label: 'Likely to Reoccur',
        description: 'Recurring vehicle maintenance issues suggest an inadequate preventive maintenance program',
        riskLevel: 'High',
        suggestedActions: [
          'Schedule full vehicle fleet inspection within 30 days',
          'Review PM schedule adherence across all units',
          'Implement mandatory pre-trip brake verification checklist',
        ],
      },
    ],
    notes: ['Tires replaced immediately at nearest service center', 'Vehicle passed re-inspection same day'],
  },
  {
    id: 'HZTC-004',
    date: '2024-05-03',
    level: 'III',
    type: 'Compliance',
    location: { city: 'Dallas', state: 'TX' },
    driverName: 'Sarah Williams',
    vin: '5FNRL5H40AB123456',
    vehicleMake: 'Volvo',
    vehicleModel: 'VNL 760',
    vehicleYear: 2023,
    plateNumber: 'TX3456S',
    plateState: 'TX',
    reportNumber: 'TXW050300456',
    reportState: 'TX',
    startTime: '13:20',
    endTime: '14:10',
    facility: 'FMCSA Office - Dallas District',
    driverOOS: false,
    vehicleOOS: false,
    severityScore: 3,
    status: 'Resolved',
    violations: [
      {
        code: '395.8(k)(1)',
        description: "Driver failing to retain or produce ELD user's manual upon request",
        severity: 'Minor',
        basicCategory: 'HOS Compliance',
        timeWeight: 1,
        oos: false,
      },
    ],
    aiInsights: [],
    notes: ['Manual provided to driver during inspection', 'Driver ELD training completed 05/05'],
  },
];

// ── Northeast Express Trucking (USDOT 715394) — 7 inspections, severe risk ──
const northeastRich: RichInspection[] = [
  {
    id: 'NEEX-001',
    date: '2025-03-15',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Buffalo', state: 'NY' },
    driverName: 'Thomas Brown',
    vin: '1FUJGLBG4PLBA5678',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2021,
    plateNumber: 'NY6612T',
    plateState: 'NY',
    reportNumber: 'NYI031500123',
    reportState: 'NY',
    startTime: '08:10',
    endTime: '09:45',
    facility: 'I-90 New York State Thruway Scale',
    driverOOS: true,
    vehicleOOS: true,
    severityScore: 9,
    status: 'New',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — multiple brake chambers inoperative on drive axle',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 3,
        oos: true,
      },
      {
        code: '391.11(b)(4)',
        description: 'Medical certificate — operating a CDL vehicle while self-certified as excepted with SDLA',
        severity: 'Major',
        basicCategory: 'Driver Qualification',
        timeWeight: 3,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'repeat-violation',
        label: 'Repeat Critical Issues',
        description: 'This carrier has had 4 critical brake violations in the past 12 months',
        riskLevel: 'High',
        suggestedActions: [
          'Implement mandatory brake inspection before every dispatch',
          'Engage third-party PM audit within 30 days',
          'Place carrier on enhanced monitoring watchlist',
        ],
      },
    ],
    notes: [],
  },
  {
    id: 'NEEX-002',
    date: '2025-02-08',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Newark', state: 'NJ' },
    driverName: 'Jessica Garcia',
    vin: '3AKJHHDRXPSGM7788',
    vehicleMake: 'Kenworth',
    vehicleModel: 'T680',
    vehicleYear: 2020,
    plateNumber: 'NJ4423J',
    plateState: 'NJ',
    reportNumber: 'NJW020800456',
    reportState: 'NJ',
    startTime: '11:30',
    endTime: '12:45',
    facility: 'NJ Turnpike Commercial Vehicle Station',
    driverOOS: false,
    vehicleOOS: true,
    severityScore: 8,
    status: 'New',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — brake lining contaminated by grease/oil',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 3,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'high-csa-impact',
        label: 'High CSA Impact',
        description: 'Vehicle Maintenance BASIC is at severe risk level — 48% OOS rate vs 21% national',
        riskLevel: 'High',
        suggestedActions: [
          'Emergency PM audit for all fleet units',
          'Review lubrication schedules and procedures',
        ],
      },
    ],
    notes: [],
  },
  {
    id: 'NEEX-003',
    date: '2024-12-19',
    level: 'II',
    type: 'Roadside',
    location: { city: 'Hartford', state: 'CT' },
    driverName: 'Michael Smith',
    vin: '1XPWD49X3ED221144',
    vehicleMake: 'Peterbilt',
    vehicleModel: '579',
    vehicleYear: 2019,
    plateNumber: 'CT8856M',
    plateState: 'CT',
    reportNumber: 'CTE121900789',
    reportState: 'CT',
    startTime: '14:00',
    endTime: '14:50',
    facility: 'I-91 DOT Inspection Station',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 7,
    status: 'In Progress',
    violations: [
      {
        code: '395.8(e)(1)',
        description: 'False record of duty status — driver exceeded 14-hour on-duty limit per ELD data',
        severity: 'Major',
        basicCategory: 'HOS Compliance',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'audit-risk',
        label: 'Compliance Audit Risk',
        description: 'Combined HOS and vehicle violations elevate targeted audit probability significantly',
        riskLevel: 'High',
        suggestedActions: [
          'Conduct internal HOS compliance audit',
          'Review driver dispatch records for past 60 days',
        ],
      },
    ],
    notes: [],
  },
  {
    id: 'NEEX-004',
    date: '2024-10-05',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Boston', state: 'MA' },
    driverName: 'Angela Davis',
    vin: '1FUJGLBG4NLBA9900',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2021,
    plateNumber: 'MA3345A',
    plateState: 'MA',
    reportNumber: 'MAE100500234',
    reportState: 'MA',
    startTime: '09:45',
    endTime: '11:20',
    facility: 'MA Turnpike Commercial Vehicle Enforcement',
    driverOOS: true,
    vehicleOOS: true,
    severityScore: 9,
    status: 'Resolved',
    violations: [
      {
        code: '395.8(e)(1)',
        description: 'False record of duty status — unaccounted driving time exceeding 2 hours',
        severity: 'Major',
        basicCategory: 'HOS Compliance',
        timeWeight: 2,
        oos: true,
      },
      {
        code: '391.11(b)(4)',
        description: 'Medical certificate — expired medical card, driver continued operating',
        severity: 'Major',
        basicCategory: 'Driver Qualification',
        timeWeight: 2,
        oos: true,
      },
    ],
    aiInsights: [
      {
        type: 'repeat-violation',
        label: 'Repeat HOS + Medical',
        description: 'Driver has both HOS and medical certificate violations — high individual driver risk',
        riskLevel: 'High',
        suggestedActions: [
          'Place driver on administrative hold pending corrective action',
          'Complete full driver qualification file audit',
        ],
      },
    ],
    notes: ['Driver placed on 30-day probation', 'Medical certificate renewed 10/08'],
  },
  {
    id: 'NEEX-005',
    date: '2024-08-01',
    level: 'I',
    type: 'Roadside',
    location: { city: 'New York City', state: 'NY' },
    driverName: 'William White',
    vin: '3AKJHHDRXPSGM9922',
    vehicleMake: 'Kenworth',
    vehicleModel: 'T680',
    vehicleYear: 2020,
    plateNumber: 'NY8834W',
    plateState: 'NY',
    reportNumber: 'NYW080100567',
    reportState: 'NY',
    startTime: '16:00',
    endTime: '17:10',
    facility: 'I-278 Goethals Bridge Commercial Inspection',
    driverOOS: false,
    vehicleOOS: true,
    severityScore: 8,
    status: 'Resolved',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — pushrod travel exceeds limit on steer and drive axles',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 1,
        oos: true,
      },
    ],
    aiInsights: [],
    notes: ['Vehicle towed for repairs'],
  },
  {
    id: 'NEEX-006',
    date: '2024-06-02',
    level: 'II',
    type: 'Roadside',
    location: { city: 'Philadelphia', state: 'PA' },
    driverName: 'Patricia Martinez',
    vin: '1XPWD49X3ED223366',
    vehicleMake: 'Peterbilt',
    vehicleModel: '389',
    vehicleYear: 2018,
    plateNumber: 'PA7789P',
    plateState: 'PA',
    reportNumber: 'PAI060200891',
    reportState: 'PA',
    startTime: '13:15',
    endTime: '14:00',
    facility: 'I-95 Pennsylvania DOT Station',
    driverOOS: true,
    vehicleOOS: false,
    severityScore: 6,
    status: 'Resolved',
    violations: [
      {
        code: '391.11(b)(4)',
        description: 'Medical certificate — driver operating with revoked medical examiner certificate',
        severity: 'Major',
        basicCategory: 'Driver Qualification',
        timeWeight: 1,
        oos: true,
      },
    ],
    aiInsights: [],
    notes: [],
  },
  {
    id: 'NEEX-007',
    date: '2024-04-08',
    level: 'I',
    type: 'Roadside',
    location: { city: 'Newark', state: 'NJ' },
    driverName: 'Steven Johnson',
    vin: '1FUJGLBG4MLBA1155',
    vehicleMake: 'Freightliner',
    vehicleModel: 'Cascadia',
    vehicleYear: 2019,
    plateNumber: 'NJ2267S',
    plateState: 'NJ',
    reportNumber: 'NJE040800345',
    reportState: 'NJ',
    startTime: '10:00',
    endTime: '11:15',
    facility: 'NJ Turnpike Authority Scale House',
    driverOOS: false,
    vehicleOOS: true,
    severityScore: 8,
    status: 'Resolved',
    violations: [
      {
        code: '396.3(a)(1)',
        description: 'Brakes out of adjustment — air brake system pressure below minimum',
        severity: 'Critical',
        basicCategory: 'Vehicle Maintenance',
        timeWeight: 1,
        oos: true,
      },
    ],
    aiInsights: [],
    notes: [],
  },
];

/** Map of USDOT → rich inspection records (single source of truth) */
export const CARRIER_RICH_INSPECTIONS: Record<string, RichInspection[]> = {
  '491180': acmeRich,       // ACME Transport — 6 inspections
  '847291': midwestRich,    // Midwest Logistics — 2 inspections
  '562843': deltaRich,      // Delta Freight — 4 inspections
  '934521': haztechRich,    // HazTech Carriers — 4 inspections
  '715394': northeastRich,  // Northeast Express — 7 inspections
};
