import { CarrierBrief } from './types';

export const mockCarriers: CarrierBrief[] = [
  {
    id: 'acme-transport',
    carrierName: 'ACME Transport LLC',
    usdot: '491180',
    mc: '123456',
    status: 'Active',
    operationType: 'Interstate / For-Hire',
    powerUnits: 42,
    drivers: 38,
    mcs150Updated: '2025-07-14',
    dataFreshness: 'Snapshot daily / SMS monthly',
    overallRisk: 'Elevated',
    trend: 'Worsening',
    confidence: 'Moderate',
    executiveMemo: 'This carrier presents elevated risk driven primarily by vehicle-maintenance deficiencies and hazmat documentation gaps. The 34.1% vehicle out-of-service rate is significantly above the 21% national benchmark, and 12-month trend data shows consistent deterioration in maintenance controls. Crash frequency remains moderate but maintenance-related severity indicators warrant close monitoring. Recommended actions focus on operational controls that can yield measurable improvement within 90-180 days.',
    trendSummary: 'Vehicle-maintenance exposure has worsened over the last 12 months, while driver-related indicators have remained comparatively stable. Recent movement suggests operational controls should be prioritized over broad policy changes.',
    metrics: {
      overallOOS: 28.4,
      overallOOSDelta: 7.8,
      vehicleOOS: 34.1,
      vehicleOOSDelta: 11.0,
      driverOOS: 7.2,
      driverOOSDelta: 0.8,
      crashes24mo: 4,
      crashesTrend: 'Flat',
      basicExposure: '2 categories high',
      mcs150Freshness: 'Current',
    },
    riskChips: {
      maintenance: 'Elevated',
      crash: 'Moderate',
      hazmat: 'Elevated',
      driver: 'Moderate',
      admin: 'Low',
    },
    topRiskDrivers: [
      'Vehicle maintenance',
      'Hazmat paperwork/process',
      'Closed enforcement history',
    ],
    riskDriverDetails: [
      {
        title: 'Vehicle Maintenance Deficiencies',
        description: 'Vehicle OOS rate of 34.1% is 13 points above national benchmark. Primary issues: brake systems, lighting, and tire conditions.',
        severity: 'high',
      },
      {
        title: 'Hazmat Documentation Gaps',
        description: 'Recent inspections flagged shipping paper errors and placard issues. 3 hazmat-related violations in past 6 months.',
        severity: 'high',
      },
      {
        title: 'Historical Enforcement Actions',
        description: 'One closed enforcement case from 2024. Pattern suggests recurring compliance challenges.',
        severity: 'medium',
      },
    ],
    whatChanged: [
      'Vehicle OOS worsened vs prior period',
      'Maintenance-related violations increased',
      'Driver-related exposure roughly stable',
    ],
    whatChangedItems: [
      { label: 'Vehicle OOS Rate', direction: 'up', detail: '+5.2 pts over 6 months' },
      { label: 'Maintenance Violations', direction: 'up', detail: '23% increase vs prior period' },
      { label: 'Driver OOS Rate', direction: 'stable', detail: 'Within normal variance' },
      { label: 'Crash Frequency', direction: 'stable', detail: 'No significant change' },
    ],
    scoreContributions: [
      { category: 'Maintenance', weight: 30, score: 72, contribution: 32 },
      { category: 'Crash', weight: 20, score: 45, contribution: 18 },
      { category: 'Driver', weight: 15, score: 38, contribution: 12 },
      { category: 'Hazmat', weight: 15, score: 65, contribution: 20 },
      { category: 'Trend', weight: 15, score: 58, contribution: 14 },
      { category: 'Admin Freshness', weight: 5, score: 15, contribution: 4 },
    ],
    aiSummary:
      'Elevated risk profile driven primarily by vehicle-maintenance and hazmat-related issues. Vehicle out-of-service performance is materially above benchmark, crash exposure is moderate, and recent trends suggest maintenance controls are deteriorating faster than driver-related controls. The fastest path to improvement is stronger defect-closeout discipline, maintenance gate audits, and hazmat paperwork quality checks.',
    fixPlan: [
      {
        title: 'Weekly maintenance gate audit',
        description: 'Implement weekly pre-trip inspection verification and gate audit process to catch defects before roadside encounters',
        impact: 'High',
        effort: 'Medium',
        expectedEffect: 'Reduce vehicle OOS rate by 8-12 pts within 6 months',
      },
      {
        title: 'Trailer / lighting / brake defect closeout discipline',
        description: 'Strengthen repair verification and defect closeout documentation processes, especially for lighting and brake systems',
        impact: 'High',
        effort: 'Medium',
        expectedEffect: 'Address primary vehicle violation categories',
      },
      {
        title: 'Hazmat shipping paper and placard QA',
        description: 'Implement pre-departure hazmat documentation review and placard verification checklist',
        impact: 'High',
        effort: 'Low',
        expectedEffect: 'Eliminate hazmat paperwork violations',
      },
      {
        title: 'Roadside inspection coaching for drivers',
        description: 'Train drivers on inspection procedures, required documents, and professional interaction with enforcement',
        impact: 'Medium',
        effort: 'Low',
        expectedEffect: 'Reduce driver-related violations and improve inspection outcomes',
      },
      {
        title: 'Review disputable items for DataQs follow-up',
        description: 'Audit recent violations for errors or disputable items and file DataQs challenges where appropriate',
        impact: 'Low',
        effort: 'Low',
        expectedEffect: 'Potentially remove 1-2 violations from record',
      },
    ],
    trendData: {
      vehicleOOS: [
        { month: 'Mar 24', value: 22.1 },
        { month: 'Apr 24', value: 24.3 },
        { month: 'May 24', value: 26.8 },
        { month: 'Jun 24', value: 28.2 },
        { month: 'Jul 24', value: 29.5 },
        { month: 'Aug 24', value: 31.2 },
        { month: 'Sep 24', value: 32.8 },
        { month: 'Oct 24', value: 33.4 },
        { month: 'Nov 24', value: 34.1 },
        { month: 'Dec 24', value: 33.9 },
        { month: 'Jan 25', value: 34.5 },
        { month: 'Feb 25', value: 34.1 },
      ],
      driverOOS: [
        { month: 'Mar 24', value: 6.1 },
        { month: 'Apr 24', value: 6.4 },
        { month: 'May 24', value: 6.8 },
        { month: 'Jun 24', value: 6.5 },
        { month: 'Jul 24', value: 6.9 },
        { month: 'Aug 24', value: 7.2 },
        { month: 'Sep 24', value: 7.4 },
        { month: 'Oct 24', value: 7.1 },
        { month: 'Nov 24', value: 7.3 },
        { month: 'Dec 24', value: 7.0 },
        { month: 'Jan 25', value: 7.2 },
        { month: 'Feb 25', value: 7.2 },
      ],
      inspections: [
        { month: 'Mar 24', value: 12, violations: 8 },
        { month: 'Apr 24', value: 15, violations: 11 },
        { month: 'May 24', value: 14, violations: 10 },
        { month: 'Jun 24', value: 16, violations: 12 },
        { month: 'Jul 24', value: 13, violations: 10 },
        { month: 'Aug 24', value: 17, violations: 14 },
        { month: 'Sep 24', value: 15, violations: 12 },
        { month: 'Oct 24', value: 18, violations: 15 },
        { month: 'Nov 24', value: 16, violations: 13 },
        { month: 'Dec 24', value: 14, violations: 11 },
        { month: 'Jan 25', value: 19, violations: 16 },
        { month: 'Feb 25', value: 17, violations: 14 },
      ],
    },
    source: 'mock' as const,
    lastRefreshed: new Date().toISOString(),
    sourceNotes: ['This is mock demonstration data'],
    dataCoverage: ['All fields are simulated for demonstration purposes']
  },
  {


    id: 'midwest-logistics',
    carrierName: 'Midwest Logistics Partners',
    usdot: '847291',
    mc: '456789',
    status: 'Active',
    operationType: 'Interstate / For-Hire',
    powerUnits: 128,
    drivers: 142,
    mcs150Updated: '2025-09-22',
    dataFreshness: 'Snapshot daily / SMS monthly',
    overallRisk: 'Low',
    trend: 'Improving',
    confidence: 'High',
    executiveMemo: 'This carrier demonstrates strong operational discipline with consistently low out-of-service rates and an improving 12-month trend. The 12.4% vehicle OOS rate is well below the 21% national benchmark, and driver compliance is excellent at 4.1%. No significant red flags identified. Recommended for standard monitoring cadence.',
    trendSummary: 'All key metrics have shown consistent improvement over the past 12 months. Vehicle OOS rates decreased steadily while inspection volume increased, indicating both improved compliance and operational growth.',
    metrics: {
      overallOOS: 14.2,
      overallOOSDelta: -6.4,
      vehicleOOS: 12.4,
      vehicleOOSDelta: -8.6,
      driverOOS: 4.1,
      driverOOSDelta: -2.3,
      crashes24mo: 2,
      crashesTrend: 'Decreasing',
      basicExposure: 'None high',
      mcs150Freshness: 'Current',
    },
    riskChips: {
      maintenance: 'Low',
      crash: 'Low',
      hazmat: 'Low',
      driver: 'Low',
      admin: 'Low',
    },
    topRiskDrivers: [
      'Minor hours-of-service documentation gaps',
      'Fleet age increasing (avg 4.2 years)',
      'Recent growth may stress capacity',
    ],
    riskDriverDetails: [
      {
        title: 'HOS Documentation',
        description: 'Minor ELD log discrepancies noted in 2 recent inspections. Low severity, easily correctable.',
        severity: 'low',
      },
      {
        title: 'Fleet Age Trajectory',
        description: 'Average fleet age has increased from 3.1 to 4.2 years. Monitor for maintenance impact.',
        severity: 'low',
      },
      {
        title: 'Growth Capacity',
        description: '18% fleet expansion in 12 months. Scaling processes important to maintain compliance.',
        severity: 'low',
      },
    ],
    whatChanged: [
      'Vehicle OOS improved significantly',
      'Zero new crashes in past 6 months',
      'Driver compliance strengthened',
    ],
    whatChangedItems: [
      { label: 'Vehicle OOS Rate', direction: 'down', detail: '-4.8 pts over 6 months' },
      { label: 'Crash Frequency', direction: 'down', detail: 'No crashes in 6 months' },
      { label: 'Driver OOS Rate', direction: 'down', detail: '-1.2 pts improvement' },
      { label: 'Fleet Size', direction: 'up', detail: '+18% capacity growth' },
    ],
    scoreContributions: [
      { category: 'Maintenance', weight: 30, score: 18, contribution: 8 },
      { category: 'Crash', weight: 20, score: 15, contribution: 6 },
      { category: 'Driver', weight: 15, score: 12, contribution: 4 },
      { category: 'Hazmat', weight: 15, score: 10, contribution: 3 },
      { category: 'Trend', weight: 15, score: 8, contribution: 2 },
      { category: 'Admin Freshness', weight: 5, score: 5, contribution: 1 },
    ],
    aiSummary:
      'Low risk profile with strong operational fundamentals and an improving trajectory. All key metrics are significantly below national benchmarks. Recent fleet growth should be monitored to ensure compliance processes scale appropriately, but current indicators are uniformly positive.',
    fixPlan: [
      {
        title: 'Maintain current compliance programs',
        description: 'Continue existing maintenance and driver compliance processes that have driven improvement',
        impact: 'High',
        effort: 'Low',
        expectedEffect: 'Sustain current low-risk profile',
      },
      {
        title: 'Address minor HOS documentation gaps',
        description: 'Review ELD procedures and provide refresher training on log documentation',
        impact: 'Low',
        effort: 'Low',
        expectedEffect: 'Eliminate minor documentation findings',
      },
      {
        title: 'Plan for fleet renewal',
        description: 'Develop equipment replacement schedule as fleet ages to prevent maintenance drift',
        impact: 'Medium',
        effort: 'Medium',
        expectedEffect: 'Maintain low maintenance risk as fleet ages',
      },
    ],
    trendData: {
      vehicleOOS: [
        { month: 'Mar 24', value: 18.2 },
        { month: 'Apr 24', value: 17.1 },
        { month: 'May 24', value: 16.4 },
        { month: 'Jun 24', value: 15.8 },
        { month: 'Jul 24', value: 15.2 },
        { month: 'Aug 24', value: 14.6 },
        { month: 'Sep 24', value: 14.1 },
        { month: 'Oct 24', value: 13.5 },
        { month: 'Nov 24', value: 13.1 },
        { month: 'Dec 24', value: 12.8 },
        { month: 'Jan 25', value: 12.6 },
        { month: 'Feb 25', value: 12.4 },
      ],
      driverOOS: [
        { month: 'Mar 24', value: 5.8 },
        { month: 'Apr 24', value: 5.5 },
        { month: 'May 24', value: 5.2 },
        { month: 'Jun 24', value: 5.0 },
        { month: 'Jul 24', value: 4.8 },
        { month: 'Aug 24', value: 4.6 },
        { month: 'Sep 24', value: 4.5 },
        { month: 'Oct 24', value: 4.4 },
        { month: 'Nov 24', value: 4.3 },
        { month: 'Dec 24', value: 4.2 },
        { month: 'Jan 25', value: 4.1 },
        { month: 'Feb 25', value: 4.1 },
      ],
      inspections: [
        { month: 'Mar 24', value: 22, violations: 8 },
        { month: 'Apr 24', value: 25, violations: 7 },
        { month: 'May 24', value: 24, violations: 6 },
        { month: 'Jun 24', value: 28, violations: 7 },
        { month: 'Jul 24', value: 26, violations: 5 },
        { month: 'Aug 24', value: 30, violations: 6 },
        { month: 'Sep 24', value: 28, violations: 5 },
        { month: 'Oct 24', value: 32, violations: 6 },
        { month: 'Nov 24', value: 29, violations: 4 },
        { month: 'Dec 24', value: 27, violations: 5 },
        { month: 'Jan 25', value: 31, violations: 4 },
        { month: 'Feb 25', value: 28, violations: 4 },
      ],
    },
    source: 'mock' as const,
    lastRefreshed: new Date().toISOString(),
    sourceNotes: ['This is mock demonstration data'],
    dataCoverage: ['All fields are simulated for demonstration purposes']
  },
  {


    id: 'delta-freight',
    carrierName: 'Delta Freight Services Inc',
    usdot: '562843',
    mc: '789012',
    status: 'Active',
    operationType: 'Interstate / For-Hire',
    powerUnits: 67,
    drivers: 71,
    mcs150Updated: '2025-04-08',
    dataFreshness: 'Snapshot daily / SMS monthly',
    overallRisk: 'Moderate',
    trend: 'Stable',
    confidence: 'High',
    executiveMemo: 'This carrier presents a moderate risk profile with stable performance across key metrics. Vehicle and driver OOS rates are slightly above national benchmarks but not at concerning levels. The stable trend indicates neither improvement nor deterioration. Recommended for standard monitoring with attention to maintenance controls.',
    trendSummary: 'Performance has remained consistent over the past 12 months with minimal variance in key metrics. This stability suggests operational processes are established but not improving.',
    metrics: {
      overallOOS: 24.1,
      overallOOSDelta: 3.5,
      vehicleOOS: 26.8,
      vehicleOOSDelta: 4.8,
      driverOOS: 6.4,
      driverOOSDelta: 0.0,
      crashes24mo: 3,
      crashesTrend: 'Flat',
      basicExposure: '1 category marginal',
      mcs150Freshness: 'Current',
    },
    riskChips: {
      maintenance: 'Moderate',
      crash: 'Moderate',
      hazmat: 'Low',
      driver: 'Moderate',
      admin: 'Low',
    },
    topRiskDrivers: [
      'Vehicle maintenance slightly elevated',
      'Driver fitness marginal BASIC',
      'Hours-of-service compliance gaps',
    ],
    riskDriverDetails: [
      {
        title: 'Vehicle Maintenance',
        description: 'Vehicle OOS at 26.8% is ~6 points above benchmark. Primary findings in brake and lighting systems.',
        severity: 'medium',
      },
      {
        title: 'Driver Fitness BASIC',
        description: 'Driver fitness BASIC percentile at 68%. Medical certificate and qualification file issues noted.',
        severity: 'medium',
      },
      {
        title: 'Hours-of-Service',
        description: 'Several HOS violations in recent inspections. Log management procedures may need review.',
        severity: 'medium',
      },
    ],
    whatChanged: [
      'Overall metrics stable quarter-over-quarter',
      'No significant trend movement',
      'Fleet size unchanged',
    ],
    whatChangedItems: [
      { label: 'Vehicle OOS Rate', direction: 'stable', detail: 'Within +/- 2 pts variance' },
      { label: 'Driver OOS Rate', direction: 'stable', detail: 'No meaningful change' },
      { label: 'Crash Frequency', direction: 'stable', detail: 'Consistent with historical pattern' },
      { label: 'BASIC Percentiles', direction: 'stable', detail: 'No category changes' },
    ],
    scoreContributions: [
      { category: 'Maintenance', weight: 30, score: 48, contribution: 22 },
      { category: 'Crash', weight: 20, score: 42, contribution: 17 },
      { category: 'Driver', weight: 15, score: 45, contribution: 14 },
      { category: 'Hazmat', weight: 15, score: 18, contribution: 6 },
      { category: 'Trend', weight: 15, score: 35, contribution: 11 },
      { category: 'Admin Freshness', weight: 5, score: 12, contribution: 2 },
    ],
    aiSummary:
      'Moderate risk profile with stable but slightly elevated metrics. No acute concerns, but room for improvement in vehicle maintenance and driver compliance areas. The stable trend suggests current operational controls are maintaining status quo but not driving improvement.',
    fixPlan: [
      {
        title: 'Strengthen pre-trip inspection process',
        description: 'Implement more rigorous pre-trip inspection verification, focusing on brake and lighting systems',
        impact: 'Medium',
        effort: 'Low',
        expectedEffect: 'Reduce vehicle OOS rate by 4-6 pts',
      },
      {
        title: 'Driver qualification file audit',
        description: 'Review all DQ files for completeness and address medical certificate renewals proactively',
        impact: 'Medium',
        effort: 'Medium',
        expectedEffect: 'Improve driver fitness BASIC percentile',
      },
      {
        title: 'HOS compliance training',
        description: 'Provide refresher training on hours-of-service rules and ELD documentation requirements',
        impact: 'Medium',
        effort: 'Low',
        expectedEffect: 'Reduce HOS-related violations',
      },
    ],
    trendData: {
      vehicleOOS: [
        { month: 'Mar 24', value: 26.2 },
        { month: 'Apr 24', value: 27.1 },
        { month: 'May 24', value: 26.5 },
        { month: 'Jun 24', value: 26.8 },
        { month: 'Jul 24', value: 27.2 },
        { month: 'Aug 24', value: 26.4 },
        { month: 'Sep 24', value: 26.9 },
        { month: 'Oct 24', value: 27.0 },
        { month: 'Nov 24', value: 26.6 },
        { month: 'Dec 24', value: 26.8 },
        { month: 'Jan 25', value: 27.1 },
        { month: 'Feb 25', value: 26.8 },
      ],
      driverOOS: [
        { month: 'Mar 24', value: 6.2 },
        { month: 'Apr 24', value: 6.5 },
        { month: 'May 24', value: 6.3 },
        { month: 'Jun 24', value: 6.4 },
        { month: 'Jul 24', value: 6.6 },
        { month: 'Aug 24', value: 6.3 },
        { month: 'Sep 24', value: 6.5 },
        { month: 'Oct 24', value: 6.4 },
        { month: 'Nov 24', value: 6.3 },
        { month: 'Dec 24', value: 6.5 },
        { month: 'Jan 25', value: 6.4 },
        { month: 'Feb 25', value: 6.4 },
      ],
      inspections: [
        { month: 'Mar 24', value: 14, violations: 9 },
        { month: 'Apr 24', value: 16, violations: 10 },
        { month: 'May 24', value: 15, violations: 9 },
        { month: 'Jun 24', value: 17, violations: 11 },
        { month: 'Jul 24', value: 14, violations: 9 },
        { month: 'Aug 24', value: 18, violations: 12 },
        { month: 'Sep 24', value: 16, violations: 10 },
        { month: 'Oct 24', value: 15, violations: 10 },
        { month: 'Nov 24', value: 17, violations: 11 },
        { month: 'Dec 24', value: 14, violations: 9 },
        { month: 'Jan 25', value: 18, violations: 12 },
        { month: 'Feb 25', value: 16, violations: 10 },
      ],
    },
    source: 'mock' as const,
    lastRefreshed: new Date().toISOString(),
    sourceNotes: ['This is mock demonstration data'],
    dataCoverage: ['All fields are simulated for demonstration purposes']
  },
  {


    id: 'haztech-carriers',
    carrierName: 'HazTech Specialized Carriers',
    usdot: '934521',
    mc: '234567',
    status: 'Active',
    operationType: 'Interstate / For-Hire / Hazmat',
    powerUnits: 34,
    drivers: 36,
    mcs150Updated: '2025-06-30',
    dataFreshness: 'Snapshot daily / SMS monthly',
    overallRisk: 'Elevated',
    trend: 'Stable',
    confidence: 'High',
    executiveMemo: 'This hazmat-focused carrier presents elevated risk due to the nature of operations combined with above-benchmark hazmat and vehicle metrics. While driver compliance is strong and the trend is stable (not deteriorating), the hazmat-specific exposure requires careful attention. The 78th percentile hazmat BASIC indicates regulatory scrutiny potential.',
    trendSummary: 'Hazmat exposure has remained elevated but stable. Vehicle maintenance shows slight improvement while driver compliance continues to be a strength. Overall trajectory is holding steady without deterioration.',
    metrics: {
      overallOOS: 31.2,
      overallOOSDelta: 10.6,
      vehicleOOS: 29.4,
      vehicleOOSDelta: 8.4,
      driverOOS: 5.8,
      driverOOSDelta: -0.6,
      crashes24mo: 1,
      crashesTrend: 'Flat',
      basicExposure: 'Hazmat 78th percentile',
      mcs150Freshness: 'Current',
    },
    riskChips: {
      maintenance: 'Elevated',
      crash: 'Low',
      hazmat: 'Elevated',
      driver: 'Low',
      admin: 'Low',
    },
    topRiskDrivers: [
      'Hazmat BASIC percentile near intervention threshold',
      'Tank vehicle maintenance requirements',
      'Specialized equipment inspection findings',
    ],
    riskDriverDetails: [
      {
        title: 'Hazmat BASIC Exposure',
        description: '78th percentile hazmat BASIC is near the 80% intervention threshold. Shipping papers and placarding violations.',
        severity: 'high',
      },
      {
        title: 'Tank Vehicle Maintenance',
        description: 'Tank integrity and valve maintenance findings in recent inspections. Specialized equipment requires enhanced protocols.',
        severity: 'high',
      },
      {
        title: 'Inspection Finding Pattern',
        description: 'Pattern of cargo securement and tank specification violations. Documentation gaps on some shipments.',
        severity: 'medium',
      },
    ],
    whatChanged: [
      'Hazmat BASIC remained stable',
      'Vehicle maintenance slightly improved',
      'No new crash incidents',
    ],
    whatChangedItems: [
      { label: 'Hazmat BASIC', direction: 'stable', detail: 'Holding at 78th percentile' },
      { label: 'Vehicle OOS Rate', direction: 'down', detail: '-1.8 pts improvement' },
      { label: 'Crash Record', direction: 'stable', detail: 'No new incidents' },
      { label: 'Driver Compliance', direction: 'stable', detail: 'Consistently strong' },
    ],
    scoreContributions: [
      { category: 'Maintenance', weight: 30, score: 58, contribution: 26 },
      { category: 'Crash', weight: 20, score: 22, contribution: 9 },
      { category: 'Driver', weight: 15, score: 20, contribution: 6 },
      { category: 'Hazmat', weight: 15, score: 78, contribution: 35 },
      { category: 'Trend', weight: 15, score: 35, contribution: 11 },
      { category: 'Admin Freshness', weight: 5, score: 10, contribution: 2 },
    ],
    aiSummary:
      'Elevated risk profile driven by hazmat-specific exposures in a specialized carrier operation. The 78th percentile hazmat BASIC is a primary concern given proximity to intervention thresholds. Vehicle maintenance is above benchmark but stable. Driver compliance is a relative strength. Risk mitigation should focus on hazmat documentation and tank equipment protocols.',
    fixPlan: [
      {
        title: 'Hazmat documentation compliance program',
        description: 'Implement rigorous pre-trip hazmat documentation review including shipping papers, placards, and emergency response information',
        impact: 'High',
        effort: 'Medium',
        expectedEffect: 'Reduce hazmat BASIC percentile below 70%',
      },
      {
        title: 'Tank equipment inspection protocol',
        description: 'Enhance tank vehicle inspection procedures focusing on valves, fittings, and cargo containment integrity',
        impact: 'High',
        effort: 'Medium',
        expectedEffect: 'Address specialized equipment findings',
      },
      {
        title: 'Cargo securement training',
        description: 'Provide specialized training on hazmat cargo securement requirements and documentation',
        impact: 'Medium',
        effort: 'Low',
        expectedEffect: 'Reduce cargo-related violations',
      },
    ],
    trendData: {
      vehicleOOS: [
        { month: 'Mar 24', value: 32.1 },
        { month: 'Apr 24', value: 31.4 },
        { month: 'May 24', value: 30.8 },
        { month: 'Jun 24', value: 31.2 },
        { month: 'Jul 24', value: 30.5 },
        { month: 'Aug 24', value: 30.1 },
        { month: 'Sep 24', value: 29.8 },
        { month: 'Oct 24', value: 30.2 },
        { month: 'Nov 24', value: 29.6 },
        { month: 'Dec 24', value: 29.9 },
        { month: 'Jan 25', value: 29.5 },
        { month: 'Feb 25', value: 29.4 },
      ],
      driverOOS: [
        { month: 'Mar 24', value: 6.2 },
        { month: 'Apr 24', value: 6.0 },
        { month: 'May 24', value: 5.9 },
        { month: 'Jun 24', value: 5.8 },
        { month: 'Jul 24', value: 5.9 },
        { month: 'Aug 24', value: 5.7 },
        { month: 'Sep 24', value: 5.8 },
        { month: 'Oct 24', value: 5.9 },
        { month: 'Nov 24', value: 5.8 },
        { month: 'Dec 24', value: 5.7 },
        { month: 'Jan 25', value: 5.8 },
        { month: 'Feb 25', value: 5.8 },
      ],
      inspections: [
        { month: 'Mar 24', value: 8, violations: 6 },
        { month: 'Apr 24', value: 10, violations: 7 },
        { month: 'May 24', value: 9, violations: 6 },
        { month: 'Jun 24', value: 11, violations: 8 },
        { month: 'Jul 24', value: 8, violations: 5 },
        { month: 'Aug 24', value: 12, violations: 8 },
        { month: 'Sep 24', value: 10, violations: 7 },
        { month: 'Oct 24', value: 9, violations: 6 },
        { month: 'Nov 24', value: 11, violations: 7 },
        { month: 'Dec 24', value: 8, violations: 5 },
        { month: 'Jan 25', value: 13, violations: 9 },
        { month: 'Feb 25', value: 10, violations: 7 },
      ],
    },
    source: 'mock' as const,
    lastRefreshed: new Date().toISOString(),
    sourceNotes: ['This is mock demonstration data'],
    dataCoverage: ['All fields are simulated for demonstration purposes']
  },
  {


    id: 'northeast-express',
    carrierName: 'Northeast Express Trucking',
    usdot: '715394',
    mc: '567890',
    status: 'Active',
    operationType: 'Interstate / For-Hire',
    powerUnits: 89,
    drivers: 94,
    mcs150Updated: '2024-11-15',
    dataFreshness: 'Snapshot daily / SMS monthly',
    overallRisk: 'Severe',
    trend: 'Worsening',
    confidence: 'High',
    executiveMemo: 'This carrier presents severe risk with a deteriorating trajectory across multiple dimensions. The 48.2% vehicle OOS rate is more than double the national benchmark, crash frequency is elevated with 8 incidents in 24 months, and the stale MCS-150 filing raises administrative compliance questions. Intervention-level BASIC percentiles in multiple categories. Exercise extreme caution; remediation requires significant operational overhaul.',
    trendSummary: 'Performance has deteriorated significantly across all major categories over the past 12 months. Vehicle OOS rates have increased sharply, crash frequency has risen, and multiple BASIC percentiles have crossed intervention thresholds.',
    metrics: {
      overallOOS: 42.6,
      overallOOSDelta: 22.0,
      vehicleOOS: 48.2,
      vehicleOOSDelta: 27.2,
      driverOOS: 12.4,
      driverOOSDelta: 6.0,
      crashes24mo: 8,
      crashesTrend: 'Increasing',
      basicExposure: '4 categories above threshold',
      mcs150Freshness: 'Overdue',
    },
    riskChips: {
      maintenance: 'Severe',
      crash: 'Severe',
      hazmat: 'Moderate',
      driver: 'Elevated',
      admin: 'Elevated',
    },
    topRiskDrivers: [
      'Critical vehicle maintenance failures',
      'Elevated crash frequency and severity',
      'Multiple BASIC intervention thresholds exceeded',
    ],
    riskDriverDetails: [
      {
        title: 'Critical Maintenance Deficiencies',
        description: 'Vehicle OOS rate of 48.2% indicates systemic maintenance program failures. Brake, tire, and lighting issues prevalent.',
        severity: 'high',
      },
      {
        title: 'Crash Performance',
        description: '8 crashes in 24 months with 3 involving injuries. Crash indicator BASIC at 92nd percentile.',
        severity: 'high',
      },
      {
        title: 'Multi-BASIC Intervention Exposure',
        description: 'Unsafe Driving (85%), Crash Indicator (92%), Vehicle Maintenance (94%), HOS (78%) all above or near thresholds.',
        severity: 'high',
      },
    ],
    whatChanged: [
      'Vehicle OOS increased sharply (+8 pts)',
      'Additional crashes recorded',
      'BASIC percentiles worsening',
    ],
    whatChangedItems: [
      { label: 'Vehicle OOS Rate', direction: 'up', detail: '+8.1 pts in 6 months' },
      { label: 'Crash Frequency', direction: 'up', detail: '3 new crashes recorded' },
      { label: 'BASIC Percentiles', direction: 'up', detail: 'Multiple categories increased' },
      { label: 'MCS-150 Status', direction: 'up', detail: 'Now overdue for update' },
    ],
    scoreContributions: [
      { category: 'Maintenance', weight: 30, score: 94, contribution: 38 },
      { category: 'Crash', weight: 20, score: 92, contribution: 24 },
      { category: 'Driver', weight: 15, score: 65, contribution: 16 },
      { category: 'Hazmat', weight: 15, score: 42, contribution: 10 },
      { category: 'Trend', weight: 15, score: 88, contribution: 17 },
      { category: 'Admin Freshness', weight: 5, score: 68, contribution: 5 },
    ],
    aiSummary:
      'Severe risk profile with deteriorating performance across all major categories. This carrier has multiple BASIC categories at or above intervention thresholds, suggesting heightened regulatory scrutiny is likely. The combination of high crash frequency, extreme vehicle OOS rates, and worsening trends indicates fundamental operational control failures. Significant remediation investment required.',
    fixPlan: [
      {
        title: 'Emergency maintenance program overhaul',
        description: 'Implement immediate fleet-wide inspection and repair program with mandatory defect correction before dispatch',
        impact: 'High',
        effort: 'High',
        expectedEffect: 'Critical to reduce vehicle OOS rate',
      },
      {
        title: 'Driver safety intervention',
        description: 'Mandatory defensive driving training and enhanced hiring/retention standards',
        impact: 'High',
        effort: 'High',
        expectedEffect: 'Address unsafe driving and crash indicators',
      },
      {
        title: 'Update MCS-150 filing immediately',
        description: 'File updated MCS-150 to address administrative compliance gap',
        impact: 'Medium',
        effort: 'Low',
        expectedEffect: 'Resolve administrative freshness issue',
      },
      {
        title: 'Engage compliance consultant',
        description: 'Consider engaging external safety consultant to develop comprehensive remediation plan',
        impact: 'High',
        effort: 'Medium',
        expectedEffect: 'Systematic approach to multi-BASIC intervention risk',
      },
    ],
    trendData: {
      vehicleOOS: [
        { month: 'Mar 24', value: 38.2 },
        { month: 'Apr 24', value: 39.8 },
        { month: 'May 24', value: 41.2 },
        { month: 'Jun 24', value: 42.1 },
        { month: 'Jul 24', value: 43.5 },
        { month: 'Aug 24', value: 44.8 },
        { month: 'Sep 24', value: 45.6 },
        { month: 'Oct 24', value: 46.4 },
        { month: 'Nov 24', value: 47.1 },
        { month: 'Dec 24', value: 47.5 },
        { month: 'Jan 25', value: 48.0 },
        { month: 'Feb 25', value: 48.2 },
      ],
      driverOOS: [
        { month: 'Mar 24', value: 9.8 },
        { month: 'Apr 24', value: 10.2 },
        { month: 'May 24', value: 10.5 },
        { month: 'Jun 24', value: 10.8 },
        { month: 'Jul 24', value: 11.1 },
        { month: 'Aug 24', value: 11.4 },
        { month: 'Sep 24', value: 11.6 },
        { month: 'Oct 24', value: 11.9 },
        { month: 'Nov 24', value: 12.1 },
        { month: 'Dec 24', value: 12.2 },
        { month: 'Jan 25', value: 12.3 },
        { month: 'Feb 25', value: 12.4 },
      ],
      inspections: [
        { month: 'Mar 24', value: 18, violations: 16 },
        { month: 'Apr 24', value: 22, violations: 19 },
        { month: 'May 24', value: 20, violations: 18 },
        { month: 'Jun 24', value: 24, violations: 21 },
        { month: 'Jul 24', value: 19, violations: 17 },
        { month: 'Aug 24', value: 26, violations: 24 },
        { month: 'Sep 24', value: 23, violations: 21 },
        { month: 'Oct 24', value: 25, violations: 23 },
        { month: 'Nov 24', value: 22, violations: 20 },
        { month: 'Dec 24', value: 21, violations: 19 },
        { month: 'Jan 25', value: 28, violations: 26 },
        { month: 'Feb 25', value: 24, violations: 22 },
      ],
    },
    source: 'mock' as const,
    lastRefreshed: new Date().toISOString(),
    sourceNotes: ['This is mock demonstration data'],
    dataCoverage: ['All fields are simulated for demonstration purposes']
  }
];
